baseURL: https://krzwg.de/
languageCode: de-de
author:
  name: Clemens Bergmann
params:
  description: Kreuzweg Darmstadt Eberstadt # The description of your site (used on a <meta> tag)
title: Kreuzweg Darmstadt Eberstadt
theme: Blogpaper
menu:
  main:
    - name: 2021
      url: /1/
