baseURL: https://krzwg.de/
languageCode: de-de
author:
  name: Christiane & Clemens Bergmann
params:
  description: Kreuzweg Darmstadt Eberstadt # The description of your site (used on a <meta> tag)
title: Kreuzweg Eberstadt
theme: Blogpaper
enableInlineShortcodes: true
markup:
  asciidocExt:
    workingFolderCurrent: true
menu:
  main:
    - name: Stationen/Videos
      url: /21/stationen/
