---
title: "Misereor Familienkreuzweg 2021"
subtitle: "Anleitung"
---

[.fas.fa-exclamation-triangle]
Bitte halten Sie sich an Hygiene und Abstandsregeln, auch in der freien Natur.

Der Fußweg beträgt ca. 20 – 30 Minuten, hinzu kommt das Videomaterial von ca. 20 Minuten.

Wir laden Sie ein, mit ihrer Familie, einem Freund oder auch allein die Stationen in der Natur ab zu laufen.
An jeder Station befindet sich ein bemalter Stein.
Wenn sie wollen, können Sie auch einen eigenen gestalteten Stein dazulegen.
Auf der Seite link:/21/stationen[Stationen] finden Sie pro Station ein Video, welches dort betrachtet werden kann.
Zwischen den Stationen kann das Lied link:https://www.youtube.com/watch?v=s3BnS7Lr_-I[„Geh mit uns“] gesungen werden.

Es gibt zwei Alternativen der Videos:
Die eine Version ist für jüngere Kinder im Kindergartenalter gedacht.
Die andere Version ab Schulalter.
Sie unterscheiden sich nur anhand der Erzählform des Kreuzwegs Jesu.
Für die jüngeren Kinder wurde der Kreuzweg mit Erzählfiguren nacherzählt.
Für die älteren ist der Kreuzweg mit der link:https://www.donbosco-medien.de/die-idee/c-570[Erzählschiene] "link:https://www.donbosco-medien.de/t-574/4193[Der Kreuzweg Jesu]" der link:https://www.donbosco-medien.de[Don Bosco Medien GmbH] dargestellt. 

Sie benötigen für den Kreuzweg ein tragbares Wiedergabegerät für Videos, z. B. Handy, Tablet, Laptop.
Falls Sie keinen mobilen Datenvertrag besitzen oder schlechten Empfang haben, können Sie sich den link:/21/FlyerKreuzweg.pdf[Flyer] und die Videos zuhause herunterladen.
Die Videos dürfen nicht weitergegeben oder auf anderen Anbietern online gestellt werden.
Natürlich könne Sie die Videos auch zu Hause betrachten und den Weg getrennt laufen.

Bitte lassen Sie die Steine, an ihrer Stelle liegen, damit auch andere diese finden.

== Kurzbeschreibung des Video Ablaufs an den Stationen

Vor dem Kreuzweg: 	Einleitungsvideo mit Lydia Haun + Lied von David Beyer.

Je Station:		Kreuzwegerzählung + Moment der Stille + Gebet + Lied von David Beyer.

Die Berichte aus Bolivien von Misereor befinden sich nur im Flyer.
